WITH TRIPS_W_ZONES AS (
	 SELECT T.LPEP_PICKUP_DATETIME,
			T.LPEP_DROPOFF_DATETIME,
			T."PULocationID",
			T."DOLocationID",
			Z1."Zone" AS PICKUP_ZONE,
			Z2."Zone" AS DROPOFF_ZONE,
			TIP_AMOUNT
		FROM PUBLIC.GREEN_TRIPDATA_2019_09 T
		LEFT JOIN PUBLIC.ZONES Z1 ON T."PULocationID" = Z1."LocationID"
		LEFT JOIN PUBLIC.ZONES Z2 ON T."DOLocationID" = Z2."LocationID"
)
SELECT DROPOFF_ZONE,
	TIP_AMOUNT
FROM TRIPS_W_ZONES
WHERE PICKUP_ZONE = 'Astoria'
	AND DATE(DATE_TRUNC('month',LPEP_PICKUP_DATETIME)) = '2019-09-01'
ORDER BY TIP_AMOUNT DESC